### ISSUE TITLE
Traceback (most recent call last):   File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 528, in _assert_validators     validator.verify(self)   File "/usr/local/lib/python3.6/dist-packages/absl/flags/_validators.py", line 82, in verify     raise _exceptions.ValidationError(self.message) absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.

### ISSUE THREAD

**Issue by sepidina** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#2]
Seems like sequence labeling whether alone or jointly with classification has a problem with finding the data_dir.
I ran 
python run_sequence_labeling_and_text_classification.py \ --task_name=Atis \ --do_train=true \ --do_eval=true \ --data_dir=data/atis_Intent_Detection_and_Slot_Filling \ --vocab_file=pretrained_model/uncased_L-12_H-768_A-12/vocab.txt \ --bert_config_file=pretrained_model/uncased_L-12_H-768_A-12/bert_config.json \ --init_checkpoint=pretrained_model/uncased_L-12_H-768_A-12/bert_model.ckpt \ --num_train_epochs=30.0 \ --output_dir=./output/atis_join_task_epoch30/

& got the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 528, in _assert_validators
    validator.verify(self)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_validators.py", line 82, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_sequence_labeling_and_text_classification.py", line 979, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 636, in __call__
    self._assert_all_validators()
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.

**Comment by yuanxiaosc** [comment]
You can run the official Bert code first to see if it is available, https://github.com/google-research/bert

**Comment by PradyumnaGupta** [comment]
I am having the same problem and found no solution !!

**Comment by yuanxiaosc** [comment]
@PradyumnaGupta I've tried to fix it. You can try to see if other tasks are working properly.

**Comment by Java-2022** [comment]
When i am running the following code
!python C:/Users/DELL/Desktop/codeTest2/bert/run_classifier.py \
!--task_name=cola \
!--do_train=true \
!--do_eval=true \
!--do_predict=true \
!--data_dir=./data \ 
!--vocab_file=./bert/cased_L-12_H-768_A-12/vocab.txt \
!--bert_config_file=./bert/cased_L-12_H-768_A-12/bert_config.json \
!--init_checkpoint=./bert/cased_L-12_H-768_A-12/bert_model.ckpt \
!--max_seq_length=128 \
!--train_batch_size=32 \
!--learning_rate=2e-5 \
!--num_train_epochs=3.0 \
!--output_dir=./bert_output \
!--do_lower_case=False/

I am having the following problem 
@yuanxiaosc How to solve this errors
2020-02-13 13:16:01.738540: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 528, in _assert_validators
    validator.verify(self)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\flags\_validators.py", line 82, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/codeTest2/bert/run_classifier.py", line 981, in <module>
    tf.compat.v1.app.run ()
  File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\app.py", line 293, in run
    flags_parser,
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\app.py", line 362, in _run_init
    flags_parser=flags_parser,
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\app.py", line 212, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow_core\python\platform\flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 636, in __call__
    self._assert_all_validators()
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.
'--vocab_file' is not recognized as an internal or external command,
operable program or batch file.

**Comment by demongolem** [comment]
For me it was a line problem and not correctly continuing the command on a new line.  If I included all the parameters on the same line (as unreadable as it might be) then the error is removed.
