### ISSUE TITLE
运行报错Values of eval_metric_ops must be (metric_value, update_op) tuples

### ISSUE THREAD

**Issue by rookieisme** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#6]
我在运行下列命令时报错：
`python run_sequence_labeling.py \
--task_name="atis" \
--do_train=True \
--do_eval=True \
--data_dir=data/atis_Intent_Detection_and_Slot_Filling .......`
我的环境是TensorFlow=1.12，python=3.5.
报错信息如下：
`INFO:tensorflow:Error recorded from evaluation_loop: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("loss/Neg:0", shape=(?, 128), dtype=float32) for key: eval_loss
INFO:tensorflow:evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "run_sequence_labeling.py", line 741, in <module>
    tf.app.run()
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_sequence_labeling.py", line 697, in main
    result = estimator.evaluate(input_fn=eval_input_fn, steps=eval_steps)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2424, in evaluate
    rendezvous.raise_errors()
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2418, in evaluate
    name=name
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 478, in evaluate
    return _evaluate()
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 460, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1484, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1520, in _call_model_fn_eval
    features, labels, model_fn_lib.ModeKeys.EVAL, config)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1538, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 330, in as_estimator_spec
    prediction_hooks=self.prediction_hooks + hooks)
  File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/model_fn.py", line 236, in __new__
    'tuples, given: {} for key: {}'.format(value, key))
TypeError: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("loss/Neg:0", shape=(?, 128), dtype=float32) for key: eval_loss`

**Comment by yuanxiaosc** [comment]
我使用的是tensorflow1.12 python3.6，但这不一定时版本的原因，我看报错原因可能是我模型评估代码run_sequence_labeling.py 写的有问题534~564 lines，你可以暂时关闭评估功能 python run_sequence_labeling.py \ --task_name="atis" \ --do_train=True \ --do_eval=False \ --data_dir=data/atis_Intent_Detection_and_Slot_Filling，当然你可以尝试修复这个问题。

**Comment by consolexinhun** [comment]
> 我在运行下列命令时报错：
> `python run_sequence_labeling.py \ --task_name="atis" \ --do_train=True \ --do_eval=True \ --data_dir=data/atis_Intent_Detection_and_Slot_Filling .......`
> 我的环境是TensorFlow=1.12，python=3.5.
> 报错信息如下：
> `INFO:tensorflow:Error recorded from evaluation_loop: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("loss/Neg:0", shape=(?, 128), dtype=float32) for key: eval_loss INFO:tensorflow:evaluation_loop marked as finished WARNING:tensorflow:Reraising captured error Traceback (most recent call last): File "run_sequence_labeling.py", line 741, in <module> tf.app.run() File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "run_sequence_labeling.py", line 697, in main result = estimator.evaluate(input_fn=eval_input_fn, steps=eval_steps) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2424, in evaluate rendezvous.raise_errors() File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors six.reraise(typ, value, traceback) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/six.py", line 693, in reraise raise value File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2418, in evaluate name=name File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 478, in evaluate return _evaluate() File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 460, in _evaluate self._evaluate_build_graph(input_fn, hooks, checkpoint_path)) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1484, in _evaluate_build_graph self._call_model_fn_eval(input_fn, self.config)) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1520, in _call_model_fn_eval features, labels, model_fn_lib.ModeKeys.EVAL, config) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn features, labels, mode, config) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn features, labels, is_export_mode=is_export_mode) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu return self._call_model_fn(features, labels, is_export_mode=is_export_mode) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1538, in _call_model_fn return estimator_spec.as_estimator_spec() File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 330, in as_estimator_spec prediction_hooks=self.prediction_hooks + hooks) File "/home/yanglan/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/estimator/model_fn.py", line 236, in __new__ 'tuples, given: {} for key: {}'.format(value, key)) TypeError: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("loss/Neg:0", shape=(?, 128), dtype=float32) for key: eval_loss`

在`tf.estimator.ModeKeys.EVAL`的`metric_fn`函数里面，返回值dict中键对应的值必须是`tf.metrics`出来的元组
